name: card
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  font_awesome_flutter: ^8.10.0
  http: ^0.12.2
  intl: ^0.16.1
  mask_text_input_formatter: ^1.0.6
  shared_preferences: ^0.5.3
  ff_navigation_bar: ^0.1.4
  flutter_custom_credit_card_ui: ^0.0.1
  flutter_multi_carousel: ^1.0.3
  mobx: ^0.4.0
  flutter_mobx: ^0.3.4
  provider: ^4.0.1
  flutter_staggered_grid_view: "^0.3.2"
  mailer: ^3.0.4
  slide_popup_dialog: ^0.0.2
  url_launcher: ^5.5.0
  whatsapp_unilink: ^1.0.0+1
  perforated_bottom_navigation_bar: ^0.0.11
  delayed_display: ^1.1.0
  expansion_card: ^0.1.0
  percent_indicator: ^2.1.9
  tutorial: ^1.0.7
  flutter_launcher_icons: ^0.8.1
  flutter_masked_text: ^0.8.0
  toggle_switch: ^0.1.8
  animated_icon_button: ^0.3.0
  rflutter_alert: ^1.1.0
  select_form_field: "^1.1.0"
  flutter_rating_bar: ^3.2.0+1
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: '0.39.17'
  build_runner:
  mobx_codegen:



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:


    - assets/images/logocard.png
    - assets/images/logocard_bco.png
    - assets/images/img3.png
    - assets/images/card_color.png
    - assets/images/card_bco.png
    - assets/images/seta_card.png
    - assets/images/azul_gradiente.jpg
    - assets/images/ativo2.png
    - assets/images/card.png
    - assets/images/card.png
    - assets/images/alimentacao.png
    - assets/images/refeicao.png
    - assets/images/natalino.png
    - assets/images/bemEstar.png
    - assets/images/maxCard.png
    - assets/images/cantinex.png
    - assets/images/combustivel.png
    - assets/images/icon_cardpay.ico

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bahnschrift
      fonts:
        - asset: assets/fonts/BAHNSCHRIFT.ttf
        - asset: assets/fonts/BAHNSCHRIFT 1.ttf
        - asset: assets/fonts/BAHNSCHRIFT 2.ttf
        - asset: assets/fonts/BAHNSCHRIFT 3.ttf
        - asset: assets/fonts/BAHNSCHRIFT 4.ttf
        - asset: assets/fonts/BAHNSCHRIFT 5.ttf
        - asset: assets/fonts/BAHNSCHRIFT 6.ttf
        - asset: assets/fonts/BAHNSCHRIFT 7.ttf
        - asset: assets/fonts/BAHNSCHRIFT 8.ttf
        - asset: assets/fonts/BAHNSCHRIFT 9.ttf
        - asset: assets/fonts/BAHNSCHRIFT 10.ttf
        - asset: assets/fonts/BAHNSCHRIFT 11.ttf
        - asset: assets/fonts/BAHNSCHRIFT 12.ttf
        - asset: assets/fonts/BAHNSCHRIFT 13.ttf
        - asset: assets/fonts/BAHNSCHRIFT 14.ttf
        # - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cardSeta.ico"